// AUTO-GENERATED by scripts/sync_sidebar_defaults.py — DO NOT EDIT.
// Source of truth: org_llm/db.py MODEL_DEFAULTS (sidebar_* keys).
// Re-run after changing any sidebar_* default:
//   python scripts/sync_sidebar_defaults.py
//
// The plugin imports SIDEBAR_DEFAULTS from this file; panel.tsx
// uses it as the DEFAULT_CONFIG fallback when sidebar-status.json
// is missing or partial. The runtime source of truth is still
// the JSON file cli.py writes — these defaults only kick in
// before the first `org-llm launch`.

export const SIDEBAR_DEFAULTS = {
  "panel_enabled": true,
  "panel_on_home": true,
  "panel_on_session": true,
  "sections": [
    "vault",
    "active",
    "health",
    "archive",
    "engage"
  ],
  "refresh_secs": 15,
  "panel_width": 36,
  "replace_internal": [
    "sidebar-mcp",
    "sidebar-lsp",
    "sidebar-todo",
    "sidebar-files"
  ],
  "top_tags_count": 3,
  "activity_window_days": 7,
  "alert_window_hours": 6,
  "alert_limit": 3,
  "make_it_so": false,
  "stardate_show": true,
  "auto_session": true,
  "auto_session_prompt": "",
  "auto_session_delay_ms": 1500,
  "auto_session_local_model": "llama3.2",
  "auto_session_use_cloud": false,
  "slow_llm_threshold_ms": 25000,
  "prompt_char": "❯ ",
  "slow_llm_auto_relaunch": true,
  "pin_toasts": false,
  "chat_emojis": true,
  "chat_frames": true,
  "scroll_up_keys": "ctrl+up,alt+up,shift+up",
  "scroll_down_keys": "ctrl+down,alt+down,shift+down",
  "scroll_pageup_keys": "ctrl+pageup,alt+pageup,shift+pageup",
  "scroll_pagedown_keys": "ctrl+pagedown,alt+pagedown,shift+pagedown",
  "slow_llm_confirm": true
} as const;
