#!/usr/bin/env python3
"""
Regenerate the docs/img/*.svg screenshots from live CLI output.

The repo ships ~33 numbered SVGs in docs/img/ (banner, doctor, splash,
askbook, captain's log, theme studio, etc.). They were generated by
Rich's `console.save_svg()` but the generation script was never
checked in — this is that script.

Run after CLI changes that affect visible output:

    uv run python scripts/regen_screenshots.py                    # all
    uv run python scripts/regen_screenshots.py --only doctor splash
    uv run python scripts/regen_screenshots.py --no-light          # dark only
    uv run python scripts/regen_screenshots.py --list              # show registry

Capture mechanism: each entry's `fn` runs against the live CLI; we
flip `org_llm.ui.console.record = True` before the call, save the
buffered segments to SVG via Rich's exporter, and restore record=False.
The same Console instance is shared across the codebase via
`from .ui import console`, so monkey-patching the attribute reaches
every print site.

Out of scope (NOT Rich-capturable, would need ttyrec/asciinema):
  • opencode TUI surfaces (home_logo, /insights dialog, sidebar) —
    those are rendered by opentui's Solid bundle, not Rich.
  • Anything inside an interactive prompt loop (askbook --interactive).

For the TUI plugin screenshots, capture them manually with your
terminal's screenshot tool while opencode is running.
"""
from __future__ import annotations

import argparse
import os
import sys
import traceback
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from rich.terminal_theme import (
    DIMMED_MONOKAI,
    MONOKAI,
    NIGHT_OWLISH,
    SVG_EXPORT_THEME,
)

# ── Theme pairs ────────────────────────────────────────────────────────
# Dark = MONOKAI (matches the existing SVGs' palette: #c5c8c6 text on
# darker bg). Light = NIGHT_OWLISH inverted via a custom theme. Both
# render the same content; only chrome colors differ.
DARK_THEME = MONOKAI
LIGHT_THEME = SVG_EXPORT_THEME  # Rich's default light export


# ── Registry ──────────────────────────────────────────────────────────

@dataclass
class Shot:
    """One screenshot entry. `fn` is called with no args; it should
    print to the shared `org_llm.ui.console`. Width is the recording
    width (Rich's default 80 is too narrow for our LCARS chrome).
    """
    name: str                  # e.g. "01-banner" — produces <name>.svg + <name>-light.svg
    title: str                 # SVG title (shown in the rich-terminal chrome)
    fn: Callable[[], None]
    needs: set[str] = field(default_factory=set)  # "db", "ollama", "vault"
    width: int = 140
    skip_light: bool = False   # some surfaces (logos with hard-coded hex) only ship dark


def _shot_banner() -> None:
    from org_llm.ui import console, PRIDE_BANNER, trans_stripe
    console.print(PRIDE_BANNER)
    console.print(trans_stripe())


def _shot_splash_classic() -> None:
    """Full LCARS splash with the active palette (assumed classic)."""
    from org_llm.ui import console
    from org_llm.cli import _render_splash_logo
    console.print(_render_splash_logo())


def _shot_palette(name: str) -> Callable[[], None]:
    """Capture the splash with a specific LCARS palette swapped in."""
    def _fn() -> None:
        from org_llm.ui import console
        from org_llm.cli import _render_splash_logo
        # Temporarily switch palette via env override, render, restore.
        prev = os.environ.get("ORG_LLM_PALETTE")
        os.environ["ORG_LLM_PALETTE"] = name
        try:
            # Force palette module to re-resolve.
            import importlib
            from org_llm import palettes as _p
            importlib.reload(_p)
            console.print(_render_splash_logo())
        finally:
            if prev is None:
                os.environ.pop("ORG_LLM_PALETTE", None)
            else:
                os.environ["ORG_LLM_PALETTE"] = prev
    return _fn


def _shot_solidarity() -> None:
    from org_llm.ui import solidarity
    solidarity()


def _shot_doctor() -> None:
    """`org-llm doctor --no-diagnose` — deterministic checks only,
    no LLM round-trip. Run via Typer's CliRunner so the verb's full
    flow executes (it prints to the shared console)."""
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["doctor", "--no-diagnose"], catch_exceptions=False)


def _shot_models_discover() -> None:
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["models", "--discover"], catch_exceptions=False)


def _shot_models_dashboard() -> None:
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["models"], catch_exceptions=False)


def _shot_palette_picker() -> None:
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["palette"], catch_exceptions=False)


def _shot_knob_list() -> None:
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["knob", "list"], catch_exceptions=False)


def _shot_launch_dry_run() -> None:
    """NEW (Phase 16.2): the launch dry-run output now includes the
    AGENTS.md write line + custom org-llm primary agent + the slot-
    plugin file:// URI. Worth its own screenshot."""
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["launch", "--dry-run"], catch_exceptions=False)


def _shot_captains_log() -> None:
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["log", "--limit", "20"], catch_exceptions=False)


def _shot_pi_status() -> None:
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["pi", "--status"], catch_exceptions=False)


def _shot_dbt_status() -> None:
    from typer.testing import CliRunner
    from org_llm.cli import app
    runner = CliRunner()
    runner.invoke(app, ["dbt", "status"], catch_exceptions=False)


# Registry: ordered to mirror the existing numbered file naming.
# Add new entries at the end with the next available number.
SHOTS: list[Shot] = [
    Shot("01-banner",                  "org-llm — banner",         _shot_banner),
    Shot("02-doctor",                  "org-llm doctor",            _shot_doctor,
          needs={"db"}),
    Shot("05-models-discover",         "org-llm models --discover", _shot_models_discover,
          needs={"db"}),
    Shot("10-splash",                  "org-llm splash",            _shot_splash_classic,
          needs={"db"}),
    Shot("12-models-dashboard",        "org-llm models",            _shot_models_dashboard,
          needs={"db"}),
    Shot("13-captains-log",            "org-llm log",                _shot_captains_log,
          needs={"db"}),
    Shot("15-dbt-status",              "org-llm dbt status",         _shot_dbt_status,
          needs={"db"}),
    Shot("20-splash-lcars-red",        "splash · red palette",       _shot_palette("red"),
          needs={"db"}),
    Shot("21-splash-lcars-green",      "splash · green palette",     _shot_palette("green"),
          needs={"db"}),
    Shot("22-splash-lcars-gold",       "splash · gold palette",      _shot_palette("gold"),
          needs={"db"}),
    Shot("23-splash-lcars-violet",     "splash · violet palette",    _shot_palette("violet"),
          needs={"db"}),
    Shot("24-splash-lcars-classic",    "splash · classic palette",   _shot_palette("classic"),
          needs={"db"}),
    Shot("25-palette-picker",          "org-llm palette",            _shot_palette_picker,
          needs={"db"}),
    Shot("26-knob-list",               "org-llm knob list",          _shot_knob_list,
          needs={"db"}),
    Shot("29-pi-status",               "org-llm pi --status",        _shot_pi_status),
    # NEW (post-Phase 16.2) — these don't have existing files yet.
    Shot("34-launch-dry-run",          "org-llm launch --dry-run",   _shot_launch_dry_run,
          needs={"db"}),
    Shot("35-solidarity",              "solidarity banner",          _shot_solidarity),
]


# ── Capture mechanism ────────────────────────────────────────────────

def _capture(shot: Shot, *, light: bool, out_dir: Path) -> Path | None:
    from org_llm import ui as _ui
    console = _ui.console

    # Save and override width for the duration of the capture. Rich
    # uses options-based rendering so we need to push width via the
    # Console's _width attribute (private but stable).
    prev_record = console.record
    prev_width = console._width  # noqa: SLF001 — intentional reach-in
    console.record = True
    console._width = shot.width  # noqa: SLF001
    if hasattr(console, "_record_buffer"):
        console._record_buffer.clear()  # noqa: SLF001

    try:
        try:
            shot.fn()
        except Exception:
            print(f"[{shot.name}] capture raised:", file=sys.stderr)
            traceback.print_exc()
            return None
        suffix = "-light" if light else ""
        out = out_dir / f"{shot.name}{suffix}.svg"
        theme = LIGHT_THEME if light else DARK_THEME
        console.save_svg(str(out), title=shot.title, theme=theme,
                          clear=True)  # clear=True empties the buffer post-save
        return out
    finally:
        console.record = prev_record
        console._width = prev_width  # noqa: SLF001


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                       formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", nargs="+", default=None,
                          help="Substrings to filter Shot names by")
    parser.add_argument("--no-light", action="store_true",
                          help="Skip light variants")
    parser.add_argument("--list", action="store_true",
                          help="List the registry and exit")
    parser.add_argument("--out-dir", default=str(REPO_ROOT / "docs" / "img"),
                          help="Output directory for SVGs")
    args = parser.parse_args()

    if args.list:
        for s in SHOTS:
            needs = ",".join(sorted(s.needs)) or "(none)"
            print(f"  {s.name:30}  needs={needs:10}  — {s.title}")
        return 0

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Filter
    selected = SHOTS
    if args.only:
        selected = [s for s in SHOTS
                    if any(needle.lower() in s.name.lower() for needle in args.only)]
        if not selected:
            print(f"error: no Shot names match {args.only!r}. "
                   f"Run --list to see available names.", file=sys.stderr)
            return 1

    print(f"Regenerating {len(selected)} screenshot(s) → {out_dir}")
    failures: list[str] = []
    for shot in selected:
        # Dark
        try:
            out = _capture(shot, light=False, out_dir=out_dir)
            print(f"  ✓ {out.name if out else '(failed)':40}  [dark]")
        except Exception as e:
            failures.append(f"{shot.name} (dark): {e}")
            print(f"  ✗ {shot.name:40}  [dark]  {e}", file=sys.stderr)
        # Light
        if args.no_light or shot.skip_light:
            continue
        try:
            out = _capture(shot, light=True, out_dir=out_dir)
            print(f"  ✓ {out.name if out else '(failed)':40}  [light]")
        except Exception as e:
            failures.append(f"{shot.name} (light): {e}")
            print(f"  ✗ {shot.name:40}  [light]  {e}", file=sys.stderr)

    if failures:
        print(f"\n{len(failures)} capture(s) failed:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
