#!/usr/bin/env python3
"""Sync sidebar defaults from Python to TypeScript.

Reads MODEL_DEFAULTS from org_llm.db, filters to sidebar_* keys,
and writes extensions/opencode/src/sidebar-defaults.generated.ts
with the corresponding `SIDEBAR_DEFAULTS` object that the plugin's
panel.tsx imports.

When to run:
    python scripts/sync_sidebar_defaults.py

…after changing any sidebar_* default in org_llm/db.py. The
generated file is committed to git so the plugin is self-contained
at file:// URI load time (no build step required, since opencode
loads .ts directly via its embedded bun runtime).

Why codegen instead of inlining: db.py is the source of truth at
runtime — cli.py emits cfg_block in sidebar-status.json, the
plugin reads that. The TS DEFAULT_CONFIG is only used as a
fallback when the JSON file is missing or partial. Without
codegen, the TS defaults silently drifted from Python several
times during Phase 17 development.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

# Allow running this as `python scripts/sync_sidebar_defaults.py`
# from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from org_llm.db import MODEL_DEFAULTS  # noqa: E402

REPO  = Path(__file__).resolve().parent.parent
OUT   = REPO / "extensions" / "opencode" / "src" / "sidebar-defaults.generated.ts"

# Keys whose VALUE in MODEL_DEFAULTS is a comma-separated list rather
# than a single scalar. Without this hint the generator can't tell
# `"vault,active,health,archive,engage"` (csv) apart from
# `"some.url/with,commas"` (string).
CSV_KEYS = {
    "sidebar_sections",
    "sidebar_replace_internal",
}


def py_to_ts(key: str, val: str):
    """Convert a MODEL_DEFAULTS string value to its TS-typed
    counterpart. The DB stores everything as strings; TS needs
    actual booleans / numbers / arrays."""
    if key in CSV_KEYS:
        return [x.strip() for x in val.split(",") if x.strip()]
    if val.lower() in ("true", "false"):
        return val.lower() == "true"
    try:
        return int(val)
    except ValueError:
        pass
    return val  # plain string


def build_defaults() -> dict:
    out: dict = {}
    for k, v in MODEL_DEFAULTS.items():
        if not k.startswith("sidebar_"):
            continue
        short = k[len("sidebar_"):]
        out[short] = py_to_ts(k, v)
    return out


def render_ts(defaults: dict) -> str:
    body = json.dumps(defaults, indent=2, ensure_ascii=False)
    return (
        "// AUTO-GENERATED by scripts/sync_sidebar_defaults.py — DO NOT EDIT.\n"
        "// Source of truth: org_llm/db.py MODEL_DEFAULTS (sidebar_* keys).\n"
        "// Re-run after changing any sidebar_* default:\n"
        "//   python scripts/sync_sidebar_defaults.py\n"
        "//\n"
        "// The plugin imports SIDEBAR_DEFAULTS from this file; panel.tsx\n"
        "// uses it as the DEFAULT_CONFIG fallback when sidebar-status.json\n"
        "// is missing or partial. The runtime source of truth is still\n"
        "// the JSON file cli.py writes — these defaults only kick in\n"
        "// before the first `org-llm launch`.\n"
        "\n"
        f"export const SIDEBAR_DEFAULTS = {body} as const;\n"
    )


def main() -> int:
    defaults = build_defaults()
    if not defaults:
        print("error: no sidebar_* keys found in MODEL_DEFAULTS", file=sys.stderr)
        return 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render_ts(defaults))
    print(f"wrote {OUT.relative_to(REPO)} — {len(defaults)} keys")
    return 0


if __name__ == "__main__":
    sys.exit(main())
